name: Publish Docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with: 
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/kirill-samylin/MyTop
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"